### ISSUE TITLE
Create a choropleth map of the data

### ISSUE THREAD

**Issue by ns-rse** [josuttonklein/edattendances2#1]
With the data that you've prepared work through creating a choropleth map using Leaflet (see [example](https://rstudio.github.io/leaflet/choropleths.html) also a handy [video](https://www.youtube.com/watch?v=eIpiL6y1oQQ&t=37s)).

Start by aggregating attendances by LSOA and plotting those, don't need to worry about subsetting data by age/gender for now as ultimately we'll write a function that subsets the data and aggregates it as desired by the user.

**Comment by josuttonklein** [comment]
Now done - it is called 'first map' in the repo

**Comment by ns-rse** [comment]
Thanks @josuttonklein 

I found the `first map.html` and it looks great well done.

Very minor but its generally a good idea to avoid spaces in filenames and use underscores (`_`) or dashes (`-`), just makes life easier as spaces are often interpreted by computers as gaps between filenames. 

I also had a look through and think your code for this is in `downloadinglsaboundary.Rmd` which I found slightly confusing as the filename suggests it downloads data, and whilst it does this it also goes on to do the plotting (as well as doing some filtering first by the looks of it).

I've made a branch (`ns-rse/feedback`) with some comments and code in `downloadinglsaboundary.Rmd` for you to have a look at before we meet later.

You can either look at it here on GitHub (go to [here](https://github.com/josuttonklein/edattendances2) and there is button above the file listing that says `main`, click this and you can select the branch and then browse to the file).

Or you can use GitKraken to pull all changes from GitHub to your computer and switch branch there.
